### ISSUE TITLE
PASSWORD

### ISSUE THREAD

**Issue by erinaldo** [rhomicom-systems-tech-gh/Rhomicom-ERP-Desktop#12]
PASSWORD FROM ADMIN USER?

**Comment by richardamensah** [comment]
For a fresh and empty database setup username is admin and password is also admin and the system will prompt you to change.
if you restored the test database password is usually Password1 or Ghana124 for admin user. Thanks

Development and support on the desktop version has however stalled since all attention is on the web version. We will therefore encourage you to switch to the web version rather. Many Thanks
