### ISSUE TITLE
Not responding on loading some froms

### ISSUE THREAD

**Issue by ajazalise** [rhomicom-systems-tech-gh/Rhomicom-ERP-Desktop#13]
I debug application with test_database and it become un responsive after a few seconds. I am using window 8 and postgresql 12, visual studio 19. The not responding form recovers after a few seconds.

**Comment by richardamensah** [comment]
Its because Database settings have not been entered in the system. When it recovers, go to settings -> DB Settings or Config and enter in the connection details for your db.

Development and support on the desktop version has however stalled since all attention is on the web version. We will therefore encourage you to switch to the web version rather. Many Thanks
